export type JBSScalar = string | number | boolean | null;
export type JBSValue = JBSScalar | JBSScalar[];
export type JBSState = Record<string, JBSValue>;
export type JBSPersistStrategy = "memory" | "querystring" | "session" | "header";
export type JBSUiPersistStrategy = "memory" | "session" | "local" | "none";
export type JBSStreamMode = "replace" | "append" | "prepend";
export type JBSPhase = "idle" | "loading" | "success" | "unchanged" | "error";
export interface JBSRuntimeOptions {
    fetchImpl?: typeof fetch;
}
export interface JBSRequestDetail {
    action: string;
    component: HTMLElement;
    endpoint: string;
    state: JBSState;
    source: HTMLElement | HTMLFormElement | null;
}
export interface JBSStreamDetail {
    component: HTMLElement;
    key: string;
    endpoint: string;
    event: string;
    data: string;
}
export interface JBSRuntimeErrorDetail {
    context: string;
    error: unknown;
    component: HTMLElement | null;
}
export interface JBSRequestFinishedDetail {
    action: string;
    component: HTMLElement;
    endpoint: string;
    outcome: Exclude<JBSPhase, "idle" | "loading">;
    state: JBSState;
    source: HTMLElement | HTMLFormElement | null;
}
export declare const JBS_HEADERS: {
    readonly accept: "text/html";
    readonly marker: "X-JBS-Request";
    readonly component: "X-JBS-Component";
    readonly action: "X-JBS-Action";
    readonly state: "X-JBS-State";
    readonly ifNoneMatch: "If-None-Match";
    readonly etag: "ETag";
};
export declare const JBS_ACTIONS: {
    readonly filter: "filter";
    readonly page: "page";
    readonly refresh: "refresh";
    readonly row: "row";
    readonly sort: "sort";
};
export declare const JBS_PERSISTENCE: {
    readonly memory: "memory";
    readonly querystring: "querystring";
    readonly session: "session";
    readonly header: "header";
};
export declare const JBS_UI_PERSISTENCE: {
    readonly memory: "memory";
    readonly session: "session";
    readonly local: "local";
    readonly none: "none";
};
export declare const JBS_STREAM_EVENTS: {
    readonly refresh: "refresh";
};
export declare const JBS_STREAM_MODES: {
    readonly replace: "replace";
    readonly append: "append";
    readonly prepend: "prepend";
};
export declare const JBS_PHASES: {
    readonly idle: "idle";
    readonly loading: "loading";
    readonly success: "success";
    readonly unchanged: "unchanged";
    readonly error: "error";
};
export declare class JBSRuntime {
    private readonly fetchImpl;
    private readonly stateStore;
    private readonly streamStore;
    private readonly streamQueue;
    private readonly streamLastSeq;
    private readonly streamSnapshots;
    private readonly streamCacheScopes;
    private readonly streamStats;
    private readonly streamFragmentCache;
    private readonly componentEtags;
    private readonly requestAbortControllers;
    private readonly requestSeq;
    private readonly autocompleteTimers;
    private readonly autocompleteRequests;
    private readonly autocompleteControllers;
    private readonly assistTimers;
    private readonly assistSeq;
    private readonly assistControllers;
    private readonly assistHints;
    private readonly disclosureStateStore;
    private readonly tablePageCache;
    private readonly overlayReturnFocus;
    private lazyObserver;
    private devModeEnabled;
    private devModeInitialized;
    private initialized;
    constructor(options?: JBSRuntimeOptions);
    private isAbortError;
    private isNetworkLoadError;
    private reportRuntimeError;
    private runTask;
    init(): void;
    private isDevModeEnabled;
    private installDevMode;
    private markDevEvent;
    hydrate(root: ParentNode): void;
    getState(component: HTMLElement): JBSState;
    refresh(componentOrId: string | HTMLElement, patch?: JBSState): Promise<void>;
    private resolveComponent;
    private componentKey;
    private requestDetail;
    private setComponentPhase;
    private finishRequest;
    private uiPersistStrategy;
    private uiStorage;
    private serializeDisclosureState;
    private parseDisclosureState;
    private persistDisclosureState;
    private loadDisclosureState;
    private disclosureStateKey;
    private captureDisclosureState;
    private applyDisclosureState;
    private hydrateComponent;
    private observeLazyComponent;
    private activateLazyComponent;
    private hydratedState;
    private persistStrategy;
    private persistState;
    private tableCacheSignature;
    private tablePageNumber;
    private clearTablePageCache;
    private cacheCurrentTablePage;
    private tryServeTablePageFromCache;
    private streamMode;
    private streamBufferMax;
    private streamMaxRows;
    private shouldPauseStream;
    private queueStreamPayload;
    private flushStreamQueue;
    private parseStreamRows;
    private defaultStreamStats;
    private bumpStreamStats;
    private fragmentCacheFor;
    private resolveFragmentTarget;
    private applyFragmentOps;
    private applyStreamMeta;
    private finalizeStreamPatch;
    private requestRefreshFromStream;
    private tableBody;
    private tableRowById;
    private parseStreamRowHtml;
    private insertRowByPosition;
    private applyStreamOps;
    private applyRowFragments;
    private applyStreamPayload;
    private connectStream;
    private findComponent;
    private menuElements;
    private focusFirstMenuItem;
    private closeMenu;
    private openMenu;
    private toggleMenu;
    private closeAllMenus;
    private autocompleteElements;
    private autocompleteKey;
    private openAutocomplete;
    private closeAutocomplete;
    private closeAllAutocompletes;
    private focusAutocompleteOption;
    private selectAutocompleteOption;
    private overlayKey;
    private focusFirstOverlayElement;
    private openOverlay;
    private closeOverlay;
    private closeTopmostOverlay;
    private multiSelectElements;
    private hydrateMultiSelects;
    private selectedMultiSelectOptions;
    private syncMultiSelect;
    private openMultiSelect;
    private closeMultiSelect;
    private closeAllMultiSelects;
    private maybeSubmitMultiSelect;
    private disclosureElements;
    private hydrateDisclosures;
    private toggleDisclosure;
    private searchableListElements;
    private hydrateSearchableLists;
    private filterSearchableList;
    private tableSelectionInputs;
    private hydrateTableSelections;
    private syncTableSelection;
    private formStateById;
    private dateRangeElements;
    private hydrateDateRangePickers;
    private openDateRangePicker;
    private closeDateRangePicker;
    private closeAllDateRangePickers;
    private maybeSubmitDateRange;
    private applyDateRangePreset;
    private applyDateRangeCustom;
    private clearDateRange;
    private assistElements;
    private assistKey;
    private openAssistPanel;
    private closeAssistPanel;
    private closeAllAssistPanels;
    private setAssistStatus;
    private renderAssistOptions;
    private insertAssistOption;
    private buildAssistOptions;
    private loadAssistHints;
    private validateAssist;
    private requestAutocompleteOptions;
    private buildPatchFromTrigger;
    private requestComponent;
    private swapComponent;
    private handleClick;
    private handleInput;
    private handleFocusIn;
    private handleKeydown;
    private handleSubmit;
    private handlePopState;
    private handleVisibilityChange;
    private handleScroll;
}
declare global {
    interface Window {
        __JBS_DEV_MODE__?: boolean;
        JinjaBootstrapSpa: JBSRuntime;
    }
}
